modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
    modId="pamhc2trees"
    version="${file.jarVersion}"
    displayName="Pam's HarvestCraft 2 Fruit Trees"
    description='''
    Pam's HarvestCraft 2 Fruit Trees adds all new fruit trees to the game
    '''

[[dependencies.pamhc2trees]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pamhc2trees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"